## OMArk output analysis
In this notebook, we will perform a basic OMArk analysis.

In [36]:
import sys,os

In [37]:
# set paths
OMARK_RES_FOLDER = '/vol/Topic4CommonData/Module1/precomputed_output/omark/'
OMARK_PATH = '/vol/Topic4CommonData/Module1/OMArk/'
MAPPING_PATH = '/vol/Topic4CommonData/Module1/proteome_list.txt'
OUT_PATH = '~/SIBBiodiversitySummerSchool2026Topic4/Module1_AnnotationQuality/out/omark/analysis/'
# TEST PATHS
OMARK_RES_FOLDER = '/Users/spascare/data/work/dessimoz/teaching/2026/accessory_SIBBS/CommonDataModule1/precomputed_output/minidataset/omark/'
OMARK_PATH = '/Users/spascare/data/work/dessimoz/pkgs/OMArk-main'
MAPPING_PATH = '/Users/spascare/data/work/dessimoz/teaching/2026/SIBBiodiversitySummerSchool2026Topic4/CommonData/proteome_list.txt'
OUT_PATH = '/Users/spascare/data/work/dessimoz/teaching/2026/SIBBiodiversitySummerSchool2026Topic4/Module1_AnnotationQuality/out/omark/analysis/'
if not os.path.exists(OUT_PATH):
    os.mkdir(OUT_PATH)

# generate OMArk report
First of all, we will generate the standard OMArk report for all 10 species we analysed. This plot summarises most of the stats calculated by OMArk in a 3-way stacked barplot per species proteome.
- The top-most bar plot shows the total number of proteins in the proteome. Here you can immediately notice deviations from the general average.
- In the second bar plot, you can observe the completeness of the proteome. Taking the chosen reference ancestral gene pool and comparing it to this proteome, what is the proportion of the ancestral genes that is found (in single or multiple copy) or missing. A high proportion of missing genes could be indication of an incomplete genome annotation, or, biologically, a high gene loss that is typical of endosymbiosis and/or parasitism.
- In the third bar plot, you can observe the consistency of the proteome. Here you can observe the proportion of extant gene that is found in the reference ancestral gene pool (consistent), or that maps to other organisms (inconsistent, unknown, or contamination). Additionally, you can observe how many genes are present as fragments.

In [38]:
# execute python script
os.system('python {}/utils/plot_all_results.py -i {} -o {}/omark_recap.png -m {} -t'.format(OMARK_PATH,OMARK_RES_FOLDER,OUT_PATH,MAPPING_PATH))

0

# Open OMArk dataframe
Here we will create a pandas dataframe with the omark results for all proteomes

In [39]:
sys.path.append(OMARK_PATH+'/utils/')
import plot_all_results as plot_all
folders = [os.path.join(OMARK_RES_FOLDER, x) for x in next(os.walk(OMARK_RES_FOLDER))[1]]
omark_df, cont_df = plot_all.create_df_from_results(folders)
if MAPPING_PATH:
    omark_df, cont_df = plot_all.integrate_external_data(omark_df, cont_df, MAPPING_PATH, taxonomy_order=True)

In [40]:
omark_df

,Protein_number,Filename,Species name,Complete,Single,Duplicated,Expected_Duplicated,Unexpected_Duplicated,Missing,Consistent,...,Inconsistent_Partially_Mapping,Inconsistent_Fragments,Inconsistent_Structurally_Consistent,Contaminant,Contaminant_Partially_Mapping,Contaminant_Fragments,Contaminant_Structurally_Consistent,Unknown,Taxid,Taxonomy
4,23823,Homo_sapiens,Homo sapiens,97.23,88.73,8.50,7.80,0.71,2.77,97.51,...,0.09,0.20,0.89,[],0.0,0.0,0.0,1.31,Homo sapiens,"[root, cellular organisms, Eukaryota, Opisthok..."
2,27731,Crocodylus_porosus,Crocodylus porosus,91.26,52.76,38.50,38.07,0.43,8.75,98.45,...,0.15,0.05,0.06,[],0.0,0.0,0.0,1.28,Crocodylus porosus,"[root, cellular organisms, Eukaryota, Opisthok..."
9,13940,Oreotrochilus_melanogaster,Oreotrochilus melanogaster,88.70,84.72,3.98,3.79,0.19,11.31,98.95,...,0.04,0.12,0.08,[],0.0,0.0,0.0,0.81,Oreotrochilus melanogaster,"[root, cellular organisms, Eukaryota, Opisthok..."
6,15666,Columba_livia,Columba livia,94.85,91.27,3.58,3.33,0.25,5.15,98.54,...,0.10,0.13,0.17,[],0.0,0.0,0.0,1.05,Columba livia,"[root, cellular organisms, Eukaryota, Opisthok..."
1,17883,Gallus_gallus,Gallus gallus,96.25,92.50,3.75,3.19,0.55,3.75,95.56,...,0.20,0.20,0.16,[],0.0,0.0,0.0,3.88,Gallus gallus,"[root, cellular organisms, Eukaryota, Opisthok..."
3,15511,Grus_americana,Grus americana,92.63,88.08,4.55,4.27,0.28,7.38,98.76,...,0.06,0.13,0.15,[],0.0,0.0,0.0,0.91,Grus americana,"[root, cellular organisms, Eukaryota, Opisthok..."
10,19174,Taeniopygia_guttata,Taeniopygia guttata,92.10,76.09,16.01,15.54,0.46,7.90,97.96,...,0.13,0.13,0.15,[],0.0,0.0,0.0,1.63,Taeniopygia guttata,"[root, cellular organisms, Eukaryota, Opisthok..."
7,13508,Phoenicopterus_ruber,Phoenicopterus ruber,83.05,77.82,5.23,5.00,0.23,16.95,98.73,...,0.06,0.08,0.10,[],0.0,0.0,0.0,1.04,Phoenicopterus ruber,"[root, cellular organisms, Eukaryota, Opisthok..."
5,15378,Aptenodytes_forsteri,Aptenodytes forsteri,94.44,91.09,3.35,3.09,0.26,5.56,98.64,...,0.07,0.10,0.15,[],0.0,0.0,0.0,1.04,Aptenodytes forsteri,"[root, cellular organisms, Eukaryota, Opisthok..."
8,14566,Struthio_camelus,Struthio camelus,90.75,87.17,3.58,3.36,0.21,9.25,98.57,...,0.06,0.17,0.15,[],0.0,0.0,0.0,1.06,Struthio camelus,"[root, cellular organisms, Eukaryota, Opisthok..."
0,17007,Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.pep.all,Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.pep.all,98.42,97.32,1.10,0.87,0.23,1.58,95.39,...,1.08,0.28,1.36,[],0.0,0.0,0.0,1.89,None,None

In [41]:
cont_df

Empty DataFrame
Columns: [Filename, Species_name, Main_Taxon, Contaminant, Contaminant_Taxid, Number_of_Proteins, Species name]
Index: []

# Filter by contaminants
Here we will apply different filters to select the proteomes of high quality only
e.g. by contaminants

In [42]:
# add column with contaminants and fragments
omark_df['Contaminant_Total'] = omark_df['Contaminant_Partially_Mapping'] + omark_df['Contaminant_Fragments'] + omark_df['Contaminant_Structurally_Consistent']
omark_df['Fragments_Total'] = omark_df['Consistent_Fragments'] + omark_df['Inconsistent_Fragments'] + omark_df['Contaminant_Fragments']
omark_df['Partial_Mapping_Total'] = omark_df['Consistent_Partially_Mapping'] + omark_df['Inconsistent_Partially_Mapping'] + omark_df['Contaminant_Partially_Mapping']
omark_df['Inconsistent_Total'] = omark_df['Inconsistent'] + omark_df['Inconsistent_Fragments'] + omark_df['Inconsistent_Partially_Mapping'] + omark_df['Inconsistent_Structurally_Consistent']

In [43]:
#basic filters
def basic_filter(df):
    df = prot_num_filter(df,80000)
    df = missing_filter(df,80)
    df = contami_filter(df,0)
    df = fragments_filter(df,30)
    df = inconsistent_filter(df,10)
    return df

def prot_num_filter(df,thr=100000):
    return df.loc[df['Protein_number']<thr]

def missing_filter(df,thr=90):
    return df.loc[df['Missing']<thr]

def contami_filter(df,thr=0):
    return df.loc[df['Contaminant_Total']<=thr]

def fragments_filter(df,thr=40):
    return df.loc[df['Fragments_Total']<thr]

def inconsistent_filter(df,thr=40):
    return df.loc[df['Inconsistent_Total']<thr]

In [44]:
filtered_omark_df = basic_filter(omark_df)
filtered_omark_df

,Protein_number,Filename,Species name,Complete,Single,Duplicated,Expected_Duplicated,Unexpected_Duplicated,Missing,Consistent,...,Contaminant_Partially_Mapping,Contaminant_Fragments,Contaminant_Structurally_Consistent,Unknown,Taxid,Taxonomy,Contaminant_Total,Fragments_Total,Partial_Mapping_Total,Inconsistent_Total
4,23823,Homo_sapiens,Homo sapiens,97.23,88.73,8.50,7.80,0.71,2.77,97.51,...,0.0,0.0,0.0,1.31,Homo sapiens,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,1.11,0.57,2.36
2,27731,Crocodylus_porosus,Crocodylus porosus,91.26,52.76,38.50,38.07,0.43,8.75,98.45,...,0.0,0.0,0.0,1.28,Crocodylus porosus,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,1.69,5.00,0.52
9,13940,Oreotrochilus_melanogaster,Oreotrochilus melanogaster,88.70,84.72,3.98,3.79,0.19,11.31,98.95,...,0.0,0.0,0.0,0.81,Oreotrochilus melanogaster,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,20.78,1.45,0.48
6,15666,Columba_livia,Columba livia,94.85,91.27,3.58,3.33,0.25,5.15,98.54,...,0.0,0.0,0.0,1.05,Columba livia,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,18.78,1.89,0.80
1,17883,Gallus_gallus,Gallus gallus,96.25,92.50,3.75,3.19,0.55,3.75,95.56,...,0.0,0.0,0.0,3.88,Gallus gallus,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,14.81,3.19,1.12
3,15511,Grus_americana,Grus americana,92.63,88.08,4.55,4.27,0.28,7.38,98.76,...,0.0,0.0,0.0,0.91,Grus americana,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,20.77,1.48,0.68
10,19174,Taeniopygia_guttata,Taeniopygia guttata,92.10,76.09,16.01,15.54,0.46,7.90,97.96,...,0.0,0.0,0.0,1.63,Taeniopygia guttata,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,27.43,1.65,0.82
7,13508,Phoenicopterus_ruber,Phoenicopterus ruber,83.05,77.82,5.23,5.00,0.23,16.95,98.73,...,0.0,0.0,0.0,1.04,Phoenicopterus ruber,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,26.06,1.17,0.48
5,15378,Aptenodytes_forsteri,Aptenodytes forsteri,94.44,91.09,3.35,3.09,0.26,5.56,98.64,...,0.0,0.0,0.0,1.04,Aptenodytes forsteri,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,18.36,1.24,0.64
8,14566,Struthio_camelus,Struthio camelus,90.75,87.17,3.58,3.36,0.21,9.25,98.57,...,0.0,0.0,0.0,1.06,Struthio camelus,"[root, cellular organisms, Eukaryota, Opisthok...",0.0,18.17,1.65,0.76
0,17007,Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.pep.all,Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.pep.all,98.42,97.32,1.10,0.87,0.23,1.58,95.39,...,0.0,0.0,0.0,1.89,None,None,0.0,1.91,6.51,5.44